apiVersion: v1
kind: Service
metadata:
  name: react-client
  labels:
    app: react-client
spec:
  type: LoadBalancer
  selector:
    app: react-client
  ports:
    - name: http
      port: 80
      targetPort: 80
