apiVersion: v1
kind: Service
metadata:
  name: react-client
  labels:
    app: react-client
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
spec:
  type: LoadBalancer
  selector:
    app: react-client
  ports:
    - name: http
      port: 80
      targetPort: 80
